spring:
  rabbitmq:
    host: localhost
    username: rmuser
    password: rmpassword
  application:
    name: eureka-client
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies1
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

server:
  port: 9001

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

moviesapi:
  sending-queue: 9000q
  receiving-queue: 9001q