server:
  port: 8088

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      routes:
      - id: route1
        # where we send traffic
        # lb - Load Balancer (default algorithm is round Robin)
        # eureka-client - spring.application.name of the application
        uri: lb://eureka-client
        predicates:
          - Path=/movies
        filters:
          - RewritePath=/movies,/api/movies
      - id: route2
        uri: lb://eureka-client
        predicates:
          - Path=/movies/**
        filters:
          - RewritePath=/movies/(?<segment>.*),/api/movies/$\{segment}